# Generated by Django 2.1.1 on 2018-11-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='slog',
            new_name='slug',
        ),
    ]
